### PR TITLE
Update to use legacy URL

### PR DESCRIPTION
**Pull request by wrumsby**

### CODE REVIEW

**Review by davidshorter — APPROVED** [review]

**Comment by davidshorter** [comment]
Should we make this a project reference in core where contentful sdk is required ?

**Comment by davidshorter** [comment]
Should we make this a project reference in core where contentful sdk is required ?

**Comment by davidshorter** [comment]
Should we make this a project reference in core where contentful sdk is required ?

**Comment by wrumsby** [comment]
> Should we make this a project reference in core where contentful sdk is required ?

Yes

**Pull request merged**
